import { ProductCard } from "@/components/ProductCard";
import { StoreHeader } from "@/components/StoreHeader";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CircleDotDashed, PackageCheck, Sparkles, Star, Zap } from "lucide-react";
import { useState } from "react";
import { Link, useSearch } from "wouter";

const previewImage = "/manus-storage/golden-frieza-dragon-stars_47413f5e.png";
const previewProduct = { id: -1, name: "Golden Frieza — Dragon Stars", slug: "golden-frieza-preview", shortDescription: "La figura de referencia está lista para que la publiques desde el panel.", priceInCents: 0, compareAtPriceInCents: null, stock: 0, mainImageUrl: previewImage, isOffer: false };

function ProductGrid({ variant = "all", filters }: { variant?: "all" | "featured" | "offers"; filters?: { categorySlug?: string; minPrice?: number; maxPrice?: number; availableOnly?: boolean; offerOnly?: boolean } }) {
  const queryInput = variant === "featured" ? { featuredOnly: true, availableOnly: true } : variant === "offers" ? { offerOnly: true, availableOnly: true } : { availableOnly: filters?.availableOnly, categorySlug: filters?.categorySlug, minPrice: filters?.minPrice, maxPrice: filters?.maxPrice, offerOnly: filters?.offerOnly };
  const query = trpc.catalog.products.useQuery(queryInput);
  const rows = query.data ?? [];
  if (query.isLoading) return <div className="grid grid-cols-2 gap-4 md:grid-cols-4">{Array.from({ length: 4 }).map((_, index) => <div key={index} className="h-80 animate-pulse rounded-2xl border-2 border-ink bg-white/50" />)}</div>;
  if (!rows.length) return <div className="grid gap-5 md:grid-cols-[.9fr_1.1fr]"><div className="memphis-card grid min-h-72 place-items-center bg-lilac p-8 text-center"><div><span className="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-full border-2 border-ink bg-white"><Sparkles /></span><h3 className="text-2xl font-black uppercase">Tu colección empieza aquí</h3><p className="mx-auto mt-3 max-w-sm text-sm font-medium">El catálogo está listo. Ingresa al panel para registrar categorías, stock, fotos y publicar tu primera figura.</p><Link href="/admin" className="memphis-button mt-5 inline-flex">Abrir panel <ArrowRight size={17} /></Link></div></div><div className="mx-auto max-h-88 overflow-hidden rounded-2xl border-2 border-ink bg-white"><img src={previewImage} alt="Figura Golden Frieza Dragon Stars" className="h-full w-full object-contain p-5" /></div></div>;
  return <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{rows.map(row => <ProductCard key={row.product.id} product={row.product} categoryName={row.category.name} />)}</div>;
}

export default function Storefront({ catalogueMode = false }: { catalogueMode?: boolean }) {
  const categories = trpc.catalog.categories.useQuery();
  const search = useSearch();
  const queryParams = new URLSearchParams(search);
  const [minPrice, setMinPrice] = useState(queryParams.get("min") ?? "");
  const [maxPrice, setMaxPrice] = useState(queryParams.get("max") ?? "");
  const [availableOnly, setAvailableOnly] = useState(queryParams.get("disponible") === "1");
  const categorySlug = queryParams.get("categoria") || undefined;
  const offerOnly = queryParams.get("ofertas") === "1";
  const catalogFilters = { categorySlug, minPrice: minPrice ? Math.round(Number(minPrice) * 100) : undefined, maxPrice: maxPrice ? Math.round(Number(maxPrice) * 100) : undefined, availableOnly, offerOnly };
  return <div className="min-h-screen overflow-hidden bg-peach text-ink"><StoreHeader />
    {!catalogueMode && <>
      <main>
        <section className="hero-grid relative overflow-hidden border-b-2 border-ink"><i className="shape shape-circle bg-mint" /><i className="shape shape-triangle" /><i className="shape shape-square bg-lilac" /><div className="container relative grid gap-8 py-10 sm:py-14 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:py-18">
          <div className="relative z-10"><p className="eyebrow"><Zap size={14} fill="currentColor" /> Llegaron las piezas imposibles</p><h1 className="mt-4 max-w-3xl text-5xl font-black uppercase leading-[.84] tracking-[-.085em] sm:text-7xl xl:text-8xl">TU REPISA<br /><span className="text-stroke">MERECE</span><br />HISTORIA.</h1><p className="mt-6 max-w-md text-base font-semibold leading-relaxed sm:text-lg">Figuras, estatuas y ediciones especiales para quienes coleccionan con obsesión saludable.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/catalogo" className="memphis-button bg-ink text-white">Ver colección <ArrowRight size={18} /></Link><a href="#ofertas" className="memphis-button bg-sun">Cazar ofertas <Star size={18} fill="currentColor" /></a></div><div className="mt-8 flex flex-wrap gap-4 text-xs font-black uppercase tracking-wider"><span className="flex items-center gap-2"><CircleDotDashed size={18} /> Stock real</span><span className="flex items-center gap-2"><PackageCheck size={18} /> Compra protegida</span></div></div>
          <div className="relative mx-auto w-full max-w-md"><div className="absolute -right-3 top-8 h-16 w-16 rotate-12 rounded-full border-2 border-ink bg-sun" /><div className="absolute -left-8 bottom-14 h-12 w-12 rotate-45 border-2 border-ink bg-lilac" /><div className="memphis-card relative rotate-2 bg-white p-3"><div className="overflow-hidden rounded-xl border-2 border-ink bg-[#f6f1eb]"><img src={previewImage} alt="Figura Golden Frieza como referencia de colección" className="h-[400px] w-full object-contain p-5 sm:h-[480px]" /></div><div className="absolute -bottom-4 -left-5 rotate-[-7deg] border-2 border-ink bg-mint px-3 py-2 text-sm font-black uppercase">Nivel: Legendario</div></div></div>
        </div></section>
        <section className="border-b-2 border-ink bg-white py-5"><div className="container flex flex-wrap items-center justify-center gap-x-9 gap-y-3 text-xs font-black uppercase tracking-[.12em]"><span>Envíos a todo Perú</span><span className="hidden h-2 w-2 rotate-45 bg-ink sm:block" /><span>Figuras originales</span><span className="hidden h-2 w-2 rotate-45 bg-ink sm:block" /><span>Pago seguro</span></div></section>
        <section className="container py-12 sm:py-16"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow bg-mint">Selección del momento</p><h2 className="section-title mt-3">PARA PRESUMIR<br />EN TU VITRINA.</h2></div><Link href="/catalogo" className="group inline-flex items-center gap-1 text-sm font-black uppercase underline decoration-2 underline-offset-4">Ver todo <ArrowRight className="transition-transform group-hover:translate-x-1" size={16} /></Link></div><ProductGrid variant="featured" /></section>
        <section className="border-y-2 border-ink bg-lilac py-12"><div className="container"><div className="mb-6 flex flex-wrap items-center gap-3"><span className="rounded-full border-2 border-ink bg-sun px-3 py-1 text-xs font-black uppercase">Explora por universo</span><span className="h-2 w-2 rotate-45 bg-ink" /></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{(categories.data?.length ? categories.data : [{ id: 1, name: "Dragon Ball", slug: "dragon-ball", description: "Guerreros, villanos y transformaciones.", accentColor: "#FFE45C" }, { id: 2, name: "Pokémon", slug: "pokemon", description: "Entrenadores, evolución y nostalgia.", accentColor: "#B7E4C7" }, { id: 3, name: "Anime", slug: "anime", description: "Historias que salen de la pantalla.", accentColor: "#D6C2FF" }, { id: 4, name: "Gaming", slug: "gaming", description: "Personajes listos para continuar.", accentColor: "#FFB3A7" }]).map(category => <Link key={category.id} href={`/catalogo?categoria=${category.slug}`} className="memphis-card group flex min-h-43 flex-col justify-between p-5 transition-transform hover:-translate-y-1" style={{ background: category.accentColor }}><span className="text-4xl font-black leading-none">0{category.id}</span><div><h3 className="text-xl font-black uppercase">{category.name}</h3><p className="mt-1 text-sm font-semibold">{category.description}</p></div><ArrowRight className="self-end transition-transform group-hover:translate-x-1" /></Link>)}</div></div></section>
        <section id="ofertas" className="container py-12 sm:py-16"><div className="mb-6"><p className="eyebrow bg-sun">Precio con superpoderes</p><h2 className="section-title mt-3">OFERTAS QUE<br />NO DURAN MUCHO.</h2></div><ProductGrid variant="offers" /></section>
      </main>
      <footer className="border-t-2 border-ink bg-ink py-10 text-white"><div className="container grid gap-8 sm:grid-cols-[1.3fr_1fr_1fr]"><div><p className="text-3xl font-black uppercase leading-[.85] tracking-[-.07em]">Figura<br />Fiebre.</p><p className="mt-4 max-w-sm text-sm font-medium text-white/75">Tu próximo personaje favorito merece un lugar importante.</p></div><div><p className="text-xs font-black uppercase tracking-widest text-mint">Tienda</p><Link href="/catalogo" className="mt-3 block text-sm font-bold hover:text-sun">Catálogo</Link><Link href="/carrito" className="mt-2 block text-sm font-bold hover:text-sun">Carrito</Link></div><div><p className="text-xs font-black uppercase tracking-widest text-mint">Gestión</p><Link href="/admin" className="mt-3 block text-sm font-bold hover:text-sun">Panel privado</Link><p className="mt-2 text-xs text-white/60">© 2026 Figura Fiebre</p></div></div></footer>
    </>}
    {catalogueMode && <main className="container py-10 sm:py-14"><p className="eyebrow bg-lilac">Toda la colección</p><h1 className="section-title mt-3">ELIGE TU<br />PRÓXIMA PIEZA.</h1><div className="my-7 flex flex-wrap gap-2"><Link href="/catalogo" className="filter-chip">Todo</Link>{categories.data?.map(category => <Link key={category.id} href={`/catalogo?categoria=${category.slug}`} className={`filter-chip ${category.slug === categorySlug ? "bg-mint" : ""}`}>{category.name}</Link>)}<Link href="/catalogo?ofertas=1" className={`filter-chip bg-sun ${offerOnly ? "-rotate-2" : ""}`}>Ofertas</Link></div><div className="memphis-card mb-7 grid gap-3 bg-white p-4 sm:grid-cols-[1fr_1fr_auto]"><label className="form-label">Desde (S/)<input className="form-input" inputMode="decimal" value={minPrice} onChange={event => setMinPrice(event.target.value)} placeholder="0" /></label><label className="form-label">Hasta (S/)<input className="form-input" inputMode="decimal" value={maxPrice} onChange={event => setMaxPrice(event.target.value)} placeholder="Sin límite" /></label><label className="flex items-center gap-2 self-end pb-3 text-sm font-black"><input type="checkbox" checked={availableOnly} onChange={event => setAvailableOnly(event.target.checked)} /> Solo disponibles</label></div><ProductGrid filters={catalogFilters} /></main>}
  </div>;
}
