import { ShoppingBag } from "lucide-react";
import { Link } from "wouter";
import { useCart } from "@/contexts/CartContext";

type ProductCardProps = { product: { id: number; name: string; slug: string; shortDescription: string; priceInCents: number; compareAtPriceInCents: number | null; stock: number; mainImageUrl: string | null; isOffer: boolean }; categoryName?: string };
export function formatPrice(value: number) { return new Intl.NumberFormat("es-PE", { style: "currency", currency: "PEN" }).format(value / 100); }

export function ProductCard({ product, categoryName }: ProductCardProps) {
  const { addItem } = useCart();
  return <article className="group flex h-full flex-col bg-[#fbfbf9]"><Link href={`/productos/${product.slug}`} className="relative block aspect-[4/4.7] overflow-hidden bg-[#f0f0ec]">{product.mainImageUrl ? <img src={product.mainImageUrl} alt={product.name} className="h-full w-full object-contain p-5 transition-transform duration-500 group-hover:scale-[1.035]" /> : <span className="grid h-full place-items-center text-center text-xs font-bold text-ink/50">Imagen próximamente</span>}{product.isOffer && <span className="absolute left-3 top-3 bg-white px-2 py-1 text-[9px] font-extrabold uppercase tracking-wider">Oferta</span>}{product.stock < 1 && <span className="absolute bottom-3 left-3 bg-ink px-2 py-1 text-[9px] font-extrabold uppercase tracking-wider text-white">Agotado</span>}</Link><div className="flex flex-1 flex-col px-1 pb-2 pt-4"><p className="editorial-label">{categoryName ?? "Coleccionables"}</p><Link href={`/productos/${product.slug}`} className="mt-2 line-clamp-2 text-sm font-bold leading-snug hover:underline">{product.name}</Link><p className="mt-1 line-clamp-2 text-xs leading-relaxed text-ink/55">{product.shortDescription}</p><div className="mt-auto flex items-center justify-between gap-2 pt-4"><div><strong className="text-sm font-extrabold">{formatPrice(product.priceInCents)}</strong>{product.compareAtPriceInCents && <span className="ml-2 text-xs text-ink/40 line-through">{formatPrice(product.compareAtPriceInCents)}</span>}</div><button onClick={() => addItem({ productId: product.id, name: product.name, priceInCents: product.priceInCents, imageUrl: product.mainImageUrl, stock: product.stock })} disabled={product.stock < 1} className="grid h-9 w-9 place-items-center border border-ink bg-white transition-colors hover:bg-ink hover:text-white disabled:cursor-not-allowed disabled:opacity-35" aria-label={`Añadir ${product.name} al carrito`}><ShoppingBag size={16} strokeWidth={1.9} /></button></div></div></article>;
}
